# Generated by Django 6.0.4 on 2026-04-28 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_students(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    StudentProfile = apps.get_model('accounts', 'StudentProfile')

    for user in User.objects.filter(role='student'):
        StudentProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('english_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('favorite_songs', models.JSONField(blank=True, default=list)),
                ('favorite_movies', models.JSONField(blank=True, default=list)),
                ('favorite_series', models.JSONField(blank=True, default=list)),
                ('favorite_anime', models.JSONField(blank=True, default=list)),
                ('favorite_artists', models.JSONField(blank=True, default=list)),
                ('favorite_genres', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.RunPython(create_profiles_for_existing_students, migrations.RunPython.noop),
    ]
