# Generated by Django 6.0.4 on 2026-04-30 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('template_key', models.CharField(choices=[('waitlist_welcome', 'Waitlist Welcome'), ('student_welcome', 'Student Welcome'), ('inactivity_reminder', 'Inactivity Reminder'), ('ops_alert', 'Operations Alert')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='operations__status_94ddc7_idx'), models.Index(fields=['template_key', 'recipient_email'], name='operations__templat_486c47_idx')],
            },
        ),
    ]
