# Generated by Django 6.0.4 on 2026-04-24 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('charge', 'Charge'), ('music', 'Music'), ('movie_clip', 'Movie Clip'), ('anime_clip', 'Anime Clip')], default='charge', max_length=20)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('external_link', 'External Link')], default='external_link', max_length=20)),
                ('media_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_type', models.CharField(choices=[('pronunciation', 'Pronunciation')], default='pronunciation', max_length=30)),
                ('instruction_text', models.TextField()),
                ('expected_phrase_en', models.CharField(max_length=255)),
                ('expected_phrase_pt', models.CharField(max_length=255)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='learning.lesson')),
            ],
            options={
                'ordering': ['lesson__title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcript_en', models.TextField(blank=True)),
                ('transcript_pt', models.TextField(blank=True)),
                ('score_en', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_pt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
