# Generated by Django 6.0.4 on 2026-04-28 18:47

import django.db.models.deletion
from django.db import migrations, models


def populate_exercise_lines(apps, schema_editor):
    Exercise = apps.get_model('learning', 'Exercise')
    ExerciseLine = apps.get_model('learning', 'ExerciseLine')

    for exercise in Exercise.objects.all():
        ExerciseLine.objects.get_or_create(
            exercise=exercise,
            order=1,
            defaults={
                'text_en': exercise.expected_phrase_en,
                'text_pt': exercise.expected_phrase_pt,
                'phonetic_hint': '',
                'reference_start_ms': 0,
                'reference_end_ms': 0,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('charge', 'Charge'), ('music', 'Music'), ('movie_clip', 'Movie Clip'), ('series_clip', 'Series Clip'), ('anime_clip', 'Anime Clip')], default='charge', max_length=20),
        ),
        migrations.CreateModel(
            name='ExerciseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text_en', models.CharField(max_length=255)),
                ('text_pt', models.CharField(blank=True, max_length=255)),
                ('phonetic_hint', models.CharField(blank=True, max_length=255)),
                ('reference_start_ms', models.PositiveIntegerField(default=0)),
                ('reference_end_ms', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='learning.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript_en', models.TextField(blank=True)),
                ('accuracy_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pronunciation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wrong_words', models.JSONField(blank=True, default=list)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('needs_coaching', 'Needs Coaching')], default='pending', max_length=20)),
                ('exercise_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_lines', to='learning.exerciseline')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_results', to='learning.submission')),
            ],
            options={
                'ordering': ['submission_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exerciseline',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='unique_exercise_line_order'),
        ),
        migrations.RunPython(populate_exercise_lines, migrations.RunPython.noop),
    ]
